# Copyright (C) 2018  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "2"

services:
  data:
    image: seresearch/opendlv-gallery-comma.ai:2016-01-31--19-19-25

  ui:
    depends_on:
      - data
    image: seresearch/opendlv-gallery-comma.ai:ui
    network_mode: host
    ports:
      - "8080:8080"
    volumes_from:
      - data
    command: --cid=123 --stdout /opt/comma.ai-dataset/2016-01-31--19-19-25.rec

